version: '2'
services:
    openpbr-app:
        image: openpbr
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://openpbr-postgresql:5432/openpbr
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://openpbr-elasticsearch:9200
        ports:
            - 8080:8080
    openpbr-postgresql:
        extends:
            file: postgresql.yml
            service: openpbr-postgresql
    openpbr-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: openpbr-elasticsearch
