version: '2'
services:
    openpbr-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/openpbr/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=openpbr
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
