package org.openpbr.domain.enumeration;

/**
 * The ValueType enumeration.
 */
public enum ValueType {
    TEXT, LONG_TEXT, LETTER, PHONE_NUMBER, EMAIL, YES_NO, YES_ONLY, DATE, DATE_TIME, TIME, NUMBER, UNIT_INTERVAL, PERCENTAGE, INTEGER, POSITIVE_INTEGER, NEGATIVE_INTEGER, POSITIVE_OR_ZERO_INTEGER, COORDINATE, URL, FILE, IMAGE
}
